### ISSUE TITLE
colab error, pytorch lighting trainer

### ISSUE THREAD

**Issue by softmurata** [lllyasviel/ControlNet#84]
I tried to do pix2pix training scripts on google colab, but I met the following error and I could not start training...
```
TypeError: on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'
```
I use pytorch-lightning==1.9.2 and torch1.13.1+cuda11.6
Does this error occur because of newer pytorch-lighting version?
I am looking forward to your reply.

**Comment by Mikubill** [comment]
You might need to change some code to make it work with higher version of ptl:
(remove dataloader_idx param)
https://github.com/lllyasviel/ControlNet/blob/5b9908e35c43aa020695a819c6cab1b8ae2f3695/ldm/models/diffusion/ddpm.py#L591
and
https://github.com/lllyasviel/ControlNet/blob/5b9908e35c43aa020695a819c6cab1b8ae2f3695/cldm/logger.py#L74

Works with ptl=1.9.1 and torch=1.13: https://wandb.ai/nyanko-devs/control-net-test/runs/3d0rf41x

**Comment by softmurata** [comment]
Oh, Thanks for your reply
I made breakthrough this error part, but I met session crash...., I could not do pix2pix training on colab at free..

**Comment by softmurata** [comment]
How much memory  does  pix2pix training require?
I could not work on 16GB GPU... with config.py changed (save_memory=True) and batch_size = 1...

**Comment by softmurata** [comment]
sorry I could do that. Only download this [font](https://github.com/prawnpdf/prawn/blob/master/data/fonts/DejaVuSans.ttf)
`cd ControlNet
mkdir data
wget https://github.com/prawnpdf/prawn/blob/master/data/fonts/DejaVuSans.ttf -P data
`
and please go to train phase.
Thanks!!

**Comment by MasterScrat** [comment]
Would be nice to add these changes to `main`?

> You might need to change some code to make it work with higher version of ptl: (remove dataloader_idx param)
> 
> https://github.com/lllyasviel/ControlNet/blob/5b9908e35c43aa020695a819c6cab1b8ae2f3695/ldm/models/diffusion/ddpm.py#L591
> 
> 
> and
> https://github.com/lllyasviel/ControlNet/blob/5b9908e35c43aa020695a819c6cab1b8ae2f3695/cldm/logger.py#L74
> 
> Works with ptl=1.9.1 and torch=1.13: https://wandb.ai/nyanko-devs/control-net-test/runs/3d0rf41x
