### ISSUE TITLE
Inference going on forever and no error messages 

### ISSUE THREAD

**Issue by albertotono** [lllyasviel/ControlNet#492]
I am running canny.pth and got the interfere running forever when usually took few seconds (5s) with my current set up. 
![Screenshot 2023-08-03 at 10 29 23 AM](https://github.com/lllyasviel/ControlNet/assets/11828200/64bb4b2d-b55b-41ad-948a-640486997f04)

**Comment by FisherYuuri** [comment]
Have you solved the problem so far?

**Comment by muaazmetex** [comment]
Hi, I am having the same issue. But I do get an error. Have a look below.
``
Traceback (most recent call last):
  File "/home/metexlabz/miniconda3/envs/control/lib/python3.8/site-packages/gradio/queueing.py", line 338, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/metexlabz/miniconda3/envs/control/lib/python3.8/site-packages/gradio/queueing.py", line 298, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
``

**Comment by muaazmetex** [comment]
Solved by updating the gradio to the latest version.

**Comment by albertotono** [comment]
Yes but yours was a different problem "no event data" (see a different issue), you have the message on the terminal. Here I don't have any message and I updated the gradio to the latest already but the problem persists.

**Comment by yuyingyeh** [comment]
I had the same issue. Solved by updating the gradio version as well.
I followed the suggestion from another issue: https://github.com/lllyasviel/ControlNet/issues/475#issuecomment-1649835292

**Comment by FisherYuuri** [comment]
I've tried inference locally and it's working, but tapping the run button on gradio doesn't call the inference program

**Comment by FisherYuuri** [comment]
OK,I solved the problem by updating the python version to 3.8+, while needing to update to the latest version of gradio.

**Comment by albertotono** [comment]
When I update to python 3.9 it says "Your installed version is: not available". To what python version did you update to? 
Is the training still working as well?

**Comment by albertotono** [comment]
ok `pip install gradio==3.40.1` solved it for me

**Comment by Yuxiang1990** [comment]
> ok `pip install gradio==3.40.1` solved it for me

worked for me.

**Comment by KhawlahB** [comment]
> I've tried inference locally and it's working, but tapping the run button on gradio doesn't call the inference program

Hello,
I hope you doing well,
How did you perform the inference locally? can you please share with me the inference script that you have used? 

Your collaboration is highly appreciated...

@FisherYuuri

**Comment by jiajiao272727** [comment]
I got the same problem too. And I have tried to change gradio version in original 3.16.2, 3.38.0, 3.40.1, and the latest 4.29.0, but none of them works. It can running but showing error in webUI in gradio 3.16.2, 3.38.0, 3.40.1. But totally cannot work in the latest 4.29.0, with "typeerror: __init__() got an unexpected keyword argument 'socket_options'". 
May I ask does anyone have the same problem and know hwo to solve it? I guess it is still about the gradio version, and does anyone knows how can we find the appropriate version? Thank you!
