### ISSUE TITLE
AssertionError: No event data

### ISSUE THREAD

**Issue by TheLearner23** [lllyasviel/ControlNet#475]
Could you please help me figure out why I'm getting this error when I run python gradio_canny2image.py as soon as I hit run of the UI????

>python gradio_canny2image.py
logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Loaded state_dict from [./models/control_sd15_canny.pth]
Running on local URL:  http://myurladdress:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='d0g4v540ncr_0' coro=<Queue.process_events() done, defined at C:\Users\username\AppData\Local\anaconda3\envs\control\lib\site-packages\gradio\queueing.py:324> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\anaconda3\envs\control\lib\site-packages\gradio\queueing.py", line 338, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\username\AppData\Local\anaconda3\envs\control\lib\site-packages\gradio\queueing.py", line 298, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data

**Comment by nutsintheshell** [comment]
the same error occurred on my server.

**Comment by m-violet-s** [comment]
the same problem. Has anyone solved it? Please help ! Thanks

**Comment by xy-cong** [comment]
the same error as well!

**Comment by potryasas** [comment]
+

**Comment by AnaisAtos** [comment]
Same error here. I tried to update gradio but nothing changed.

**Comment by hxg-ai** [comment]
pip install gradio==3.38.0

**Comment by potryasas** [comment]
> pip install gradio==3.38.0

it didnt help

**Comment by potryasas** [comment]
conda activate control
python -m pip install --upgrade pip
pip install gradio

fixed for me

**Comment by AnaisAtos** [comment]
> conda activate control python -m pip install --upgrade pip pip install gradio
> 
> fixed for me

Worked for me too, thank you !

**Comment by albertotono** [comment]
Anyone with a similar error instead https://github.com/lllyasviel/ControlNet/issues/492 . In this case there is no error message. Just loading forever

**Comment by linrio** [comment]
same

**Comment by cd123-cd** [comment]
我一开始遇到的问题是点击run没反应，然后就关闭浏览器再打开在上传图像出现楼主一样的错误，后来更新一下gradio没反应，最后干脆指定版本3.38.0，解决了

**Comment by iris0329** [comment]
pip install gradio==3.40.1 solved it for me

accoring to this issue:
https://github.com/lllyasviel/ControlNet/issues/492#issuecomment-1675073320

**Comment by jiajiao272727** [comment]
I got the same problem too. And I have tried to change gradio version in original 3.16.2, 3.38.0, 3.40.1, and the latest 4.29.0, but none of them works. It can running but showing error in webUI in gradio 3.16.2, 3.38.0, 3.40.1. But totally cannot work in the latest 4.29.0, with "typeerror: init() got an unexpected keyword argument 'socket_options'".
May I ask does anyone have the same problem and know hwo to solve it? I guess it is still about the gradio version, and does anyone knows how can we find the appropriate version? Thank you!

**Comment by highsummer** [comment]
`pip install gradio==???` might have solved the problem, but it took too long for the pip version solver to solve.
The following loosy got me a quick resolution.

```pip install "gradio>=3.38.0,==3.*"```

**Comment by Gracesta** [comment]
`pip install gradio==3.50.1` worked for me.

**Comment by 2561681244** [comment]
> `pip install gradio==???` might have solved the problem, but it took too long for the pip version solver to solve. The following loosy got me a quick resolution.
> 
> `pip install "gradio>=3.38.0,==3.*"`

Thank you! It does work!

**Comment by keblicuey** [comment]
gradio==3.38  "error"  
gradio==3.16  "no event data"
